services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8001:3000"
    env_file:
      - ./api-gateway/.env
    networks:
      - veren

  submission-service:
    build:
      context: ./submission-service
      dockerfile: Dockerfile.dev
    container_name: submission-service
    volumes:
      - ./submission-service:/src
      - submission_node_modules:/src/node_modules
    ports:
      - "8002:3000"
    env_file:
      - ./submission-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren

  extractor-service:
    build:
      context: ./extractor-service
      dockerfile: Dockerfile.dev
    container_name: extractor-service
    volumes:
      - ./extractor-service:/src
      - extractor_node_modules:/src/node_modules
    ports:
      - "8003:3000"
    env_file:
      - ./extractor-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - ./api-gateway/postgres.env
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - veren

volumes:
  api_node_modules:
  submission_node_modules:
  extractor_node_modules:
  pgdata:


networks:
  veren:
    external: false
